### ISSUE TITLE
There are some error when i open Wnmp if mariaDB already opened

### ISSUE THREAD

**Issue by muxiaozi** [wnmp/wnmp#89]
**I usually close the Wnmp Control Panel after open nginx, mysql and php, but when i open Wnmp again, this error will occur!**

System.InvalidOperationException: 无法打开计算机“DESKTOP-7BM4B4A”上的 Wnmp-MariaDB 服务。 ---> System.ComponentModel.Win32Exception: 指定的服务未安装。
   --- End of internal exception stack trace ---
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at System.ServiceProcess.ServiceController.get_Status()
   at Wnmp.Programs.MariaDBProgram.IsRunning()
   at Wnmp.UI.MainFrm.AppsRunningTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I love the wnmp, although i couldn't write some code~~~

**Comment by x64architecture** [comment]
Thanks for reporting the issue! Will be fixed ASAP.
